id: P001691
initial_creation_type: ocr
source_metadata:
  id: bdr:W5329
  title: ཙོང་ཁ་པའི་རྣམ་ཐར་ཐུབ་བསྟན་མཛེས་པའི་རྒྱན་གཅིག་ངོ་མཚར་ནོར་བུའི་ཕྲེང་བ།
  author: ''
  volumes:
    46ae3b05f75b474895aad5f184bce65c:
      image_group_id: I1GS105513
      title: ''
      volume_number: 1
      total_pages: 664
